---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20952.
--- DateTime: 2023/6/5 15:31
---

--- 使用lua脚本保证redis释放锁的原子性
--把查看是不是自己的锁和删除锁放到一条redis命令中
if(redis.call('GET',KEYS[1])==ARGV[1])
then
    return redis.call('DEL',KEYS[1])
end
return 0